apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: algn48/nti-app
        ports:
        - containerPort: 5000
